import platform

#help(platform)
#print(dir(platform))
print(platform.processor())
print(platform.architecture())
print(platform.machine())
print(platform.node())
print(platform.platform())
print(platform.system())
print(platform.uname())
print(platform.python_build())
print(platform.java_ver())
print(platform.python_version())
print(platform.python_branch())
print(platform.win32_edition())
print(platform.python_compiler())
print(platform.python_implementation())
print(platform.python_revision())
print(platform.win32_ver())